apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-migration
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Migration"
    rbac.authorization.halo.run/display-name: "Migration"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:PluginMigrate:migrate"]
  # This role template file will be removed in future versions
  deletionTimestamp: 2024-02-18T08:27:41.257531Z
rules:
  - apiGroups: ["plugin.halo.run"]
    resources: ["plugins/rss-parse"]
    resourceNames: ["PluginMigrate"]
    verbs: ["create"]
